# INTEL CONFIDENTIAL
#
# © 2014-2021 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may not
# use, modify, copy, publish, distribute, disclose or transmit this software or
# the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.

name: Status

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TC_NBFEEDER_HOST: syssim_tc_pdx
  __NBTARGET_FILE: /nfs/site/gen/adm/netbatch/megafeeder/nbtarget/root/syssim_tc_pdx/.nbtarget

jobs:
  lint:
    runs-on: [self-hosted, ec]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check format
      run: make lint

  test:
    runs-on: [self-hosted, ec]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run unit tests
      run: make test

# vim: ts=2:sw=2
