name: docu-py-wasp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docu-py-wasp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run pdoc
      run: |
        # Install dependencies
        sudo apt-get update -y
        sudo apt-get install -y
        
        # Install python 3.7
        sudo apt install python3.7 -y
        
        # Make python 3.7 the default
        sudo echo "alias python=python3.7" >> ~/.bashrc
        sudo export PATH=${PATH}:/usr/bin/python3.7
        sudo /bin/bash -c "source ~/.bashrc"
        # Install pip
        sudo apt install python3-pip -y
        sudo python3 -m pip install --upgrade pip
        #install requests-kerberos
        sudo apt-get install gcc 
        sudo apt-get install python-dev -y
        sudo apt-get install libkrb5-dev -y
        sudo pip install pywinrm[kerberos]
        sudo pip install requests-kerberos
        #install pdoc
        sudo pip install pdoc3
        sudo pdoc --html py_wasp/py_wasp.py --overwrite
# vim: ts=2:sw=2
