name: docu-py-wasp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docu-py-wasp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.7

    - name: run pdoc
      run: |
        # Install dependencies
        sudo apt-get update -y
        sudo apt-get install -y
        
        # Install pip
        sudo apt install python3-pip -y
        python -m pip install --upgrade pip
        #install requests-kerberos
        sudo apt-get install gcc 
        sudo apt-get install python-dev -y
        sudo apt-get install libkrb5-dev -y
        pip install pywinrm[kerberos]
        pip install requests-kerberos
        #install pdoc
        sudo pip install pdoc3
        sudo pdoc --html py_wasp/py_wasp.py --overwrite
    - name: Commit and push changes
      run: |
        git config --global user.name "yagelmai"
        git config --global user.email "yagel.maimon@intel.com"
        git add -A
        git commit -m "create py_wasp documantation"
        git push
# vim: ts=2:sw=2
