name: docu2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docu-py-wasp:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: run pdoc
      run: |
        pdoc --html py_wasp/py_wasp.py --overwrite -o docs
        pwd
        pwd
        ls
        mv /home/yagelmai/play-ground/pdoc-task/my_repo/docu-py-wasp/runner/actions-runner/_work/docu-py-wasp/docu-py-wasp/docs/py_wasp.html /home/yagelmai/play-ground/pdoc-task/my_repo/docu-py-wasp/runner/actions-runner/_work/docu-py-wasp/docu-py-wasp/docs/index.html
        
    - name: Commit and push changes
      run: |
        git config --global user.name "yagelmai"
        git config --global user.email "yagel.maimon@intel.com"
        git branch -u origin/master
        git add -A
        git commit -m "create py_wasp documantation"
        git pull
        git push
