name: docu-py-wasp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docu-py-wasp:
    runs-on: [self-hosted, ec]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install pip
      run: |
        sudo apt install python3-pip -y
        python -m pip install --upgrade pip
        
    - name: install requests-kerberos
      run: |
        sudo apt-get install gcc 
        sudo apt-get install python3-dev -y
        sudo apt-get install libkrb5-dev -y
    - name: run pdoc
      run: |
        sudo pip install pywinrm
        sudo pip install requests-kerberos
        sudo pip install pdoc3
        sudo pdoc --html py_wasp/py_wasp.py --overwrite -o docs
        mv /home/runner/work/docu-py-wasp/docu-py-wasp/docs/py_wasp.html /home/runner/work/docu-py-wasp/docu-py-wasp/docs/index.html 
        
    - name: Commit and push changes
      run: |
        git config --global user.name "yagelmai"
        git config --global user.email "yagel.maimon@intel.com"
        git add -A
        git commit -m "create py_wasp documantation"
        git push
# vim: ts=2:sw=2
